export const analyticsEvents = {
  appInstalled: "app_installed",
  appOpened: "app_opened",

  onboardingViewed: "onboarding_viewed",
  onboardingSlideViewed: "onboarding_slide_viewed",
  onboardingCompleted: "onboarding_completed",
  howItWorksViewed: "how_it_works_viewed",
  howItWorksSlideViewed: "how_it_works_slide_viewed",
  howItWorksCompleted: "how_it_works_completed",
  profileDetailsStepViewed: "profile_details_step_viewed",
  profileDetailsCompleted: "profile_details_completed",
  planReadyViewed: "plan_ready_viewed",
  underageBlocked: "underage_blocked",
  socialProofViewed: "social_proof_viewed",
  socialProofCompleted: "social_proof_completed",
  authViewed: "auth_viewed",
  appleLoginTapped: "apple_login_tapped",
  appleLoginCanceled: "apple_login_canceled",
  appleLoginFailed: "apple_login_failed",
  userRegistered: "user_registered",

  paywallViewed: "paywall_viewed",
  paywallCtaTapped: "paywall_cta_tapped",
  paywallWheelSpun: "paywall_wheel_spun",
  paywallPurchaseSucceeded: "paywall_purchase_succeeded",
  paywallPurchaseFailed: "paywall_purchase_failed",
  paywallRestoreTapped: "paywall_restore_tapped",

  homeViewed: "home_viewed",
  firstDayGuideViewed: "first_day_guide_viewed",
  firstDayGuideSlideViewed: "first_day_guide_slide_viewed",
  firstDayGuideCompleted: "first_day_guide_completed",
  waterLogged: "water_logged",
  stepsGoalCompleted: "steps_goal_completed",
  pointsGoalCompleted: "points_goal_completed",

  dietViewed: "diet_viewed",
  dietFoodAdded: "diet_food_added",
  dietRecipeAdded: "diet_recipe_added",
  dietScanAdded: "diet_scan_added",
  articleViewed: "article_viewed",
} as const;
