export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  scrollViewBottomPadding: 100,
  tabBarBaseHeight: 60,
  tabBarTopRadius: 18,
  borderRadius: 8,
  calendarWeightDotSize: 6,
  calendarTodayBorderWidth: 2,
  rounded: 100,
  componentGap: 16,
  homescreenGap: 24,
  screenMarginTop: 25,
};
