import { create } from "zustand";

const dummyWeather = {
  location: {
    name: "Hudiksvall",
    region: "Gavleborgs Lan",
    country: "Sweden",
    lat: 61.733,
    lon: 17.113,
    tz_id: "Europe/Stockholm",
    localtime_epoch: 1748592436,
    localtime: "2025-05-30 10:07",
  },
  current: {
    last_updated_epoch: 1748592000,
    last_updated: "2025-05-30 10:00",
    temp_c: 11.7,
    temp_f: 53.1,
    is_day: 1,
    condition: {
      text: "Patchy rain nearby",
      icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
      code: 1063,
    },
    wind_mph: 8.7,
    wind_kph: 14,
    wind_degree: 172,
    wind_dir: "S",
    pressure_mb: 1004,
    pressure_in: 29.65,
    precip_mm: 0.06,
    precip_in: 0,
    humidity: 64,
    cloud: 92,
    feelslike_c: 10.1,
    feelslike_f: 50.3,
    windchill_c: 10.1,
    windchill_f: 50.3,
    heatindex_c: 11.7,
    heatindex_f: 53.1,
    dewpoint_c: 5.1,
    dewpoint_f: 41.2,
    vis_km: 10,
    vis_miles: 6,
    uv: 2.4,
    gust_mph: 13.6,
    gust_kph: 21.9,
  },
  forecast: {
    forecastday: [
      {
        date: "2025-05-30",
        date_epoch: 1748563200,
        day: {
          maxtemp_c: 14.2,
          maxtemp_f: 57.6,
          mintemp_c: 7.4,
          mintemp_f: 45.4,
          avgtemp_c: 10.7,
          avgtemp_f: 51.2,
          maxwind_mph: 12.3,
          maxwind_kph: 19.8,
          totalprecip_mm: 1.65,
          totalprecip_in: 0.06,
          totalsnow_cm: 0,
          avgvis_km: 8.3,
          avgvis_miles: 5,
          avghumidity: 76,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 94,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain nearby",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 0.6,
        },
        astro: {
          sunrise: "03:31 AM",
          sunset: "10:09 PM",
          moonrise: "05:35 AM",
          moonset: "02:07 AM",
          moon_phase: "Waxing Crescent",
          moon_illumination: 11,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
      {
        date: "2025-05-31",
        date_epoch: 1748649600,
        day: {
          maxtemp_c: 16.8,
          maxtemp_f: 62.2,
          mintemp_c: 6.8,
          mintemp_f: 44.2,
          avgtemp_c: 11.9,
          avgtemp_f: 53.4,
          maxwind_mph: 13.9,
          maxwind_kph: 22.3,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 49,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 1.4,
        },
        astro: {
          sunrise: "03:29 AM",
          sunset: "10:11 PM",
          moonrise: "07:34 AM",
          moonset: "02:07 AM",
          moon_phase: "Waxing Crescent",
          moon_illumination: 19,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
      {
        date: "2025-06-01",
        date_epoch: 1748736000,
        day: {
          maxtemp_c: 16.8,
          maxtemp_f: 62.2,
          mintemp_c: 6.3,
          mintemp_f: 43.3,
          avgtemp_c: 13,
          avgtemp_f: 55.3,
          maxwind_mph: 14.1,
          maxwind_kph: 22.7,
          totalprecip_mm: 3.88,
          totalprecip_in: 0.15,
          totalsnow_cm: 0,
          avgvis_km: 9.9,
          avgvis_miles: 6,
          avghumidity: 53,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 74,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain nearby",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 1.2,
        },
        astro: {
          sunrise: "03:27 AM",
          sunset: "10:13 PM",
          moonrise: "09:22 AM",
          moonset: "02:05 AM",
          moon_phase: "Waxing Crescent",
          moon_illumination: 29,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
    ],
  },
};
interface WeatherState {
  weather: any;
  setWeather: (weather: any) => void;
}

const useWeatherStore = create<WeatherState>((set) => ({
  weather: dummyWeather,
  setWeather: (weather) => set({ weather }),
}));

export default useWeatherStore;
